---
CVP_CONFIGLETS:
  # DEMO-management: "{{lookup('file', './configlet.txt')}}"
  # DEMO-acl: "{{lookup('file', './networks/configs/acl.cfg')}}"
  DEMO-DC1-LEAF1A: "{{lookup('file', 'renderedavd/intended/configs/DC1-LEAF1A.cfg')}}"
  DEMO-DC1-LEAF2A: "{{lookup('file', 'renderedavd/intended/configs/DC1-LEAF2A.cfg')}}"
  DEMO-DC1-LEAF3A: "{{lookup('file', 'renderedavd/intended/configs/DC1-LEAF3A.cfg')}}"
  DEMO-DC1-LEAF4A: "{{lookup('file', 'renderedavd/intended/configs/DC1-LEAF4A.cfg')}}"
  DEMO-DC1-LEAF5A: "{{lookup('file', 'renderedavd/intended/configs/DC1-LEAF5A.cfg')}}"
  DEMO-DC1-LEAF6A: "{{lookup('file', 'renderedavd/intended/configs/DC1-LEAF6A.cfg')}}"
  DEMO-DC1-SPINE1: "{{lookup('file', 'renderedavd/intended/configs/DC1-SPINE1.cfg')}}"
  DEMO-DC1-SPINE2: "{{lookup('file', 'renderedavd/intended/configs/DC1-SPINE2.cfg')}}"
  DEMO-DC1-SPINE3: "{{lookup('file', 'renderedavd/intended/configs/DC1-SPINE3.cfg')}}"
  DEMO-DC1-SPINE4: "{{lookup('file', 'renderedavd/intended/configs/DC1-SPINE4.cfg')}}"

CVP_DEVICES:
  DC1-LEAF1A:
    name: DC1-LEAF1A
    parentContainerName: TechFieldDay
    configlets:
      - DEMO-DC1-LEAF1A
  DC1-LEAF2A:
    name: DC1-LEAF2A
    parentContainerName: Demo
    configlets:
      - DEMO-DC1-LEAF2A
  DC1-LEAF3A:
    name: DC1-LEAF3A
    parentContainerName: Demo
    configlets:
      - DEMO-DC1-LEAF3A
  DC1-LEAF4A:
    name: DC1-LEAF4A
    parentContainerName: Demo
    configlets:
      - DEMO-DC1-LEAF4A
  DC1-LEAF5A:
    name: DC1-LEAF5A
    parentContainerName: Demo
    configlets:
      - DEMO-DC1-LEAF5A
  DC1-LEAF6A:
    name: DC1-LEAF6A
    parentContainerName: Demo
    configlets:
      - DEMO-DC1-LEAF6A