---
- name: Build Configurations
  hosts: DC1_FABRIC
  gather_facts: false
  tasks:

    - name: build local folders
      tags: [build]
      import_role:
        name: arista.avd.build_output_folders

    - name: generate intended variables
      tags: [build]
      import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags: [build]
      import_role:
        name: arista.avd.eos_cli_config_gen