---
- name: Send command
  hosts: leaf-101
  gather_facts: false
  tasks:

   # Alternate from the command line ansible leaf-101 -m arista.eos.eos_command -a "commands='show version | include image'"
    - name: Get version
      arista.eos.eos_command:
        commands: show version | include image
      register: switch_version

    - name: View version
      ansible.builtin.debug:
        msg: "{{ switch_version }}"

    - name: View version filtered dot
      ansible.builtin.debug:
        msg: "{{ switch_version.stdout.0 }}"

    - name: View version filtered bracket
      ansible.builtin.debug:
        msg: "{{ switch_version['stdout'][0] }}"
