---
- name: Gather all the things
  hosts: DC1
  gather_facts: true
  tasks:

    - name: View version
      ansible.builtin.debug:
        msg: "{{ ansible_net_version }}"
      register: version_check
      failed_when: ansible_net_version != "4.28.0F-26924507.4280F (engineering build)"

    - name: Create version documentation
      ansible.builtin.template:
        src: ../templates/software.j2
        dest: ../documentation/software/software.md
        mode: "u=rw"
      delegate_to: localhost
      run_once: true

    # - name: All facts
    #   debug:
    #     msg: "{{ ansible_facts }}"
