---
- name: Device backup
  hosts: DC1
  gather_facts: false
  tasks:

    - name: Save configuration for EOS devices
      arista.eos.eos_config:
        backup: true
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: ./backups
      when: ansible_network_os == "arista.eos.eos"
