---
- name: Banner Playbook
  hosts: DC1
  gather_facts: false
  tasks:

    - name: Configure login and motd banners
      arista.eos.eos_banner:
        banner: "{{ item }}"
        text: |
          {% if item == "login" %}
          Logging into {{ inventory_hostname }}
          Unauthorized access to this device is prohibited
          {% else %}
          Welcome to {{ inventory_hostname }}
          {% endif %}
        state: present
      loop:
        - login
        - motd
