---
- name: Deploy Configuration
  hosts: DC1
  gather_facts: false

  tasks:
    - name: Deploy configuration
      arista.eos.eos_config:
        src: ../intended/configs/{{ inventory_hostname }}.cfg
        replace: config
        save_when: changed
