---
- name: Simple BGP check
  hosts: DC1
  gather_facts: false
  tasks:

    - name: Get BGP
      arista.eos.eos_command:
        commands: show ip bgp summary | json
      register: bgp_check

    - name: Set fact for output
      ansible.builtin.set_fact:
        bgp_status: "{{ bgp_check.stdout.0.vrfs.default.peers }}"

    # Lookup plugin to return lists of key/value
    - name: Check BGP neighbor status
      ansible.builtin.debug:
        msg: "Neighbor {{ item.key }} is in state: {{ item.value.peerState }}"
      with_dict: "{{ bgp_status }}"
      failed_when: "item.value.peerState != 'Established'"
