---
all:
  children:
    CVP:
      hosts:
        cv_ztp:
          ansible_host: 10.90.224.175
          ansible_user: root
          ansible_password: ansible
        cv_server:
          ansible_httpapi_host: 10.90.224.175
          ansible_host: 10.90.224.175
          ansible_user: cvpadmin
          ansible_password: arista123!
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false
          ansible_network_os: eos
          ansible_httpapi_port: 443
          # Configuration to get Virtual Env information
          ansible_python_interpreter: $(which python3)
    # DC1_Fabric - EVPN Fabric running in home lab
    DC1:
      children:
        DC1_FABRIC:
          children:
            DC1_SPINES:
              hosts:
                DC1-SPINE1:
                  ansible_host: 172.20.20.9
                DC1-SPINE2:
                  ansible_host: 172.20.20.7
                DC1-SPINE3:
                  ansible_host: 172.20.20.10
                DC1-SPINE4:
                  ansible_host: 172.20.20.3
            DC1_L3LEAFS:
              children:
                DC1_LEAF1:
                  hosts:
                    DC1-LEAF1A:
                      ansible_host: 172.20.20.11
                DC1_LEAF2:
                  hosts:
                    DC1-LEAF2A:
                      ansible_host: 172.20.20.2
                DC1_LEAF3:
                  hosts:
                    DC1-LEAF3A:
                      ansible_host: 172.20.20.4
                DC1_LEAF4:
                  hosts:
                    DC1-LEAF4A:
                      ansible_host: 172.20.20.6
                DC1_LEAF5:
                  hosts:
                    DC1-LEAF5A:
                      ansible_host: 172.20.20.5
                DC1_LEAF6:
                  hosts:
                    DC1-LEAF6A:
                      ansible_host: 172.20.20.8
          vars:
            ansible_connection: httpapi
            ansible_network_os: eos
            ansible_user: cvpadmin
            # should use vault for passwords
            ansible_ssh_pass: arista123!
            ansible_become: true
            ansible_become_method: enable
            ansible_httpapi_use_ssl: true
            ansible_httpapi_validate_certs: false
        DC1_TENANTS_NETWORKS:
          children:
            DC1_L3LEAFS:
            DC1_L2LEAFS:
        DC1_SERVERS:
          children:
            DC1_L3LEAFS:
            DC1_L2LEAFS:
