---
DC1:
  children:
    DC1_FABRIC:
      children:
        DC1_SPINES:
          vars:
            type: spine
          hosts:
            spine-11:
        DC1_L3LEAFS:
          vars:
            type: l3leaf
          children:
            DC1_LEAF1:
              hosts:
                leaf-101:
            DC1_LEAF2:
              hosts:
                leaf-102:
    DC1_TENANTS_NETWORKS:
      children:
        DC1_L3LEAFS:
    DC1_SERVERS:
      children:
        DC1_L3LEAFS:
  vars:
    ansible_user: admin
    ansible_ssh_pass: admin
    ansible_network_os: arista.eos.eos
    # Configure privilege escalation
    ansible_become: true
    ansible_become_method: enable
    # HTTPAPI configuration
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
