---
# local users
local_users:
  # Username with a password
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$ICfMofvulgyrSy.I$YNucN.yK.YDdxz4dtGR2o88CxtrhQM11W5O7SkzUlQoW8PqAKZCurrK1nQ2O8j0cEPQ.aS1oMOPuPHCt2LW5r/"

# OOB Management network default gateway.
mgmt_interface: Management0
mgmt_gateway: 192.168.100.1
mgmt_interface_vrf: MGMT
mgmt_destination_networks:
  - 0.0.0.0/0

# dns servers.
name_servers:
  - 1.1.1.1
  - 8.8.8.8